# frozen_string_literal: true

source "https://rubygems.org"

gem "duoruby", path: "../.."

gem "glimmer-dsl-web", ">= 0.8.5"
gem "opal-async", "~> 1.4.1"
gem "opal-jquery", "~> 0.5.2"
gem "to_collection", ">= 2.0.1"

gem "base64", ">= 0.2"
